
# This file is generated by scripts/generate_variable.py. DO NOT MODIFY!

from shortcuts_py.variable import ContentItemClass

__all__ = [
    'App',
    'AppStoreApp',
    'Article',
    'Boolean',
    'Contact',
    'Date',
    'Dictionary',
    'Display',
    'EmailAddress',
    'EventAttendee',
    'File',
    'Folder',
    'Image',
    'ITunesMedia',
    'ITunesProduct',
    'Location',
    'MapsLink',
    'Media',
    'Number',
    'PDF',
    'PhoneNumber',
    'PhotoMedia',
    'Place',
    'RichText',
    'SafariWebPage',
    'Text',
    'URL',
    'VCard',
    'Window',
]

App = ContentItemClass.App
AppStoreApp = ContentItemClass.AppStoreApp
Article = ContentItemClass.Article
Boolean = ContentItemClass.Boolean
Contact = ContentItemClass.Contact
Date = ContentItemClass.Date
Dictionary = ContentItemClass.Dictionary
Display = ContentItemClass.Display
EmailAddress = ContentItemClass.EmailAddress
EventAttendee = ContentItemClass.EventAttendee
File = ContentItemClass.File
Folder = ContentItemClass.Folder
Image = ContentItemClass.Image
ITunesMedia = ContentItemClass.ITunesMedia
ITunesProduct = ContentItemClass.ITunesProduct
Location = ContentItemClass.Location
MapsLink = ContentItemClass.MapsLink
Media = ContentItemClass.Media
Number = ContentItemClass.Number
PDF = ContentItemClass.PDF
PhoneNumber = ContentItemClass.PhoneNumber
PhotoMedia = ContentItemClass.PhotoMedia
Place = ContentItemClass.Place
RichText = ContentItemClass.RichText
SafariWebPage = ContentItemClass.SafariWebPage
Text = ContentItemClass.Text
URL = ContentItemClass.URL
VCard = ContentItemClass.VCard
Window = ContentItemClass.Window
